name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['python=3.7', 'python=3.8', 'python=3.9', 'python=3.10']
        prompt-toolkit: ['prompt_toolkit=2', 'prompt_toolkit=3']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          set -x
          set -e
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda update -q conda
          conda info -a
          conda create -n test-environment ${{ matrix.python-version }} --file requirements.txt pytest flaky ${{ matrix.prompt-toolkit-version }}
          conda init

      - name: Run Tests
        run: |
          # Copied from .bashrc. We can't just source .bashrc because it exits
          # when the shell isn't interactive.

          # >>> conda initialize >>>
          # !! Contents within this block are managed by 'conda init' !!
          __conda_setup="$('/usr/share/miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
          if [ $? -eq 0 ]; then
              eval "$__conda_setup"
          else
              if [ -f "/usr/share/miniconda/etc/profile.d/conda.sh" ]; then
                  . "/usr/share/miniconda/etc/profile.d/conda.sh"
              else
                  export PATH="/usr/share/miniconda/bin:$PATH"
              fi
          fi
          unset __conda_setup
          # <<< conda initialize <<<

          set -x
          set -e

          conda activate test-environment

          python -We:invalid -We::SyntaxWarning -m compileall -f -q mypython
          pyflakes mypython bin/mypython
          python -m pytest -vvv --fulltrace
